name: Build Windows ZIP (stable & fast)

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    timeout-minutes: 20  # 🕒 Limitează execuția la 20 min (evită blocarea)

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Create venv, install deps and build EXE
        shell: pwsh
        run: |
          # 1️⃣ Creează un mediu virtual local
          python -m venv .\venv

          # 2️⃣ Activează mediul virtual
          .\venv\Scripts\Activate.ps1

          # 3️⃣ Upgrade pip
          python -m pip install --upgrade pip

          # 4️⃣ Instalează dependențele
          python -m pip install requests==2.31.0
          python -m pip install pyinstaller==5.13.0
          python -m pip install --extra-index-url https://PySimpleGUI.net/install PySimpleGUI==5.0.10

          # 5️⃣ Curăță orice build vechi
          if (Test-Path dist) { Remove-Item -Recurse -Force dist }
          if (Test-Path build) { Remove-Item -Recurse -Force build }

          # 6️⃣ Construiește aplicația în mod sigur (onedir)
          .\venv\Scripts\pyinstaller.exe --onedir --windowed --collect-all PySimpleGUI --name "FakeSourcesTesterPro" main_gui_pro.py

          # 7️⃣ Creează arhiva ZIP finală
          Compress-Archive -Path dist\FakeSourcesTesterPro\* -DestinationPath FakeSourcesTesterPro-windows.zip -Force

      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: FakeSourcesTesterPro-windows-zip
          path: FakeSourcesTesterPro-windows.zip
