name: Build Windows EXE (onedir safe)

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
    # ia tot codul din branch-ul curent
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Create venv, install deps and build EXE
      shell: pwsh
      run: |
        # 1. Creează un mediu virtual local
        python -m venv venv

        # 2. Activează mediul virtual
        .\venv\Scripts\Activate.ps1

        # 3. Upgrade pip
        python -m pip install --upgrade pip

        # 4. Instalează requests (dependență din core.py)
        python -m pip install requests==2.31.0

        # 5. Instalează PySimpleGUI din indexul privat oficial
        #    Asta rezolvă eroarea "module 'PySimpleGUI' has no attribute 'theme'"
        python -m pip install --upgrade --extra-index-url https://PySimpleGUI.net/install PySimpleGUI

        # 6. Instalează PyInstaller (versiunea folosită deja în proiectul tău)
        python -m pip install pyinstaller==5.13.0

        # 7. Rulează PyInstaller în modul onedir
        #    --onedir = distribuție tip folder (mai puține probleme la rulare)
        #    --windowed = fără consolă neagră în spate
        #    --name = numele exe-ului
        pyinstaller --noconfirm --onedir --windowed --name "FakeSourcesTesterPro" main_gui_pro.py

    - name: Upload EXE artifact
      uses: actions/upload-artifact@v4
      with:
        name: FakeSourcesTesterPro-windows
        path: dist/FakeSourcesTesterPro
        if-no-files-found: error
