name: Build Windows EXE (rapid)

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Create venv + install deps
        shell: pwsh
        run: |
          # 1. Creează un mediu virtual local
          python -m venv venv
          # 2. Activează venv
          .\venv\Scripts\Activate.ps1
          # 3. Upgrade pip
          python -m pip install --upgrade pip
          # 4. Instalează dependențe din requirements.txt (requests etc)
          python -m pip install -r requirements.txt
          # 5. Instalează PySimpleGUI din serverul privat + pyinstaller
          python -m pip install --extra-index-url https://PySimpleGUI.net/install PySimpleGUI
          python -m pip install pyinstaller==5.13.0

      - name: Build EXE (onefile, windowed)
        shell: pwsh
        run: |
          .\venv\Scripts\Activate.ps1
          # CONSTRUIEȘTE ONEFILE DIRECT (mult mai rapid / rezultatul e 1 singur .exe mare)
          pyinstaller `
            --noconfirm `
            --clean `
            --onefile `
            --windowed `
            --name "FakeSourcesTesterPro" `
            main_gui_pro.py

          # După build onefile, executabilul final e la dist\FakeSourcesTesterPro.exe
          dir dist

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: FakeSourcesTesterPro-windows-exe
          path: dist/FakeSourcesTesterPro.exe
