name: Build Windows ZIP (stable & fast)

on:
  workflow_dispatch: {}

jobs:
  build-windows:
    # creștem timpul maxim permis
    timeout-minutes: 60
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Create venv, install deps and build EXE
        shell: pwsh
        run: |
          Write-Host "▶ 1. Creează un mediu virtual local"
          python -m venv venv
          & .\venv\Scripts\Activate.ps1

          # upgrade pip
          python -m pip install --upgrade pip

          # dependențe standard
          pip install requests==2.31.0
          pip install pyinstaller==5.13.0

          # instalăm PySimpleGUI 5 din indexul lor privat
          pip install --extra-index-url https://PySimpleGUI.net/install PySimpleGUI==5.0.10

          Write-Host "▶ 2. Rulează PyInstaller (onedir)"
          # IMPORTANT: facem build in mod onedir (folder complet)
          # și nu mai blocăm execuția la 20 minute
          pyinstaller main_gui_pro.py `
            --name FakeSourcesTesterPro `
            --onedir `
            --noconfirm `
            --clean `
            --collect-all PySimpleGUI `
            --hidden-import PySimpleGUI

          Write-Host "▶ 3. Arhivăm folderul dist\\FakeSourcesTesterPro în ZIP pentru download"
          Compress-Archive -Path dist/FakeSourcesTesterPro -DestinationPath FakeSourcesTesterPro-windows.zip -Force

      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: FakeSourcesTesterPro-windows
          path: FakeSourcesTesterPro-windows.zip
          if-no-files-found: error
